import Head from "next/head";
import HomePage from "./components/home/Index";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </div>
  );
}
